messages:
  player-op: |
    &a&l➤  &aТы получил &lOP &aдля тестирования &bAXIOM&a!
    &e&l➤  &eВключи креатив: &6/gamemode creative
    &e&l➤  &eПерезайди на сервер, чтобы всё применилось.
    &b&l➤  &bПодробнее о моде: &9&nhttps://bm.wtf/resources/4766/&r
